# Generated by Django 3.1.7 on 2021-06-03 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0003_pupil_home_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='pupil',
            name='class_number',
            field=models.IntegerField(null=True, verbose_name='Класс зачисления'),
        ),
        migrations.AddField(
            model_name='pupil',
            name='enrollment_date',
            field=models.DateField(null=True, verbose_name='Дата зачисления'),
        ),
    ]
