# Generated by Django 3.1.7 on 2021-03-07 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0004_logogroups'),
    ]

    operations = [
        migrations.AddField(
            model_name='logogroups',
            name='choices',
            field=models.ManyToManyField(to='admin_panel.Pupil'),
        ),
    ]
