# Generated by Django 3.1.7 on 2021-03-07 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0007_auto_20210307_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logogroups',
            name='pupils',
            field=models.ManyToManyField(to='admin_panel.Pupil'),
        ),
    ]
