# Generated by Django 3.1.7 on 2021-03-07 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0008_auto_20210307_1138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logogroups',
            name='pupils',
        ),
        migrations.AddField(
            model_name='logogroups',
            name='pupils',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_panel.pupil', verbose_name='Ученик'),
        ),
    ]
