# Generated by Django 3.1.7 on 2021-03-07 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0009_auto_20210307_1146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logogroups',
            name='pupils',
        ),
        migrations.AddField(
            model_name='logogroups',
            name='pupils',
            field=models.ManyToManyField(to='admin_panel.Pupil', verbose_name='Ученик'),
        ),
    ]
