# Generated by Django 3.1.7 on 2021-03-07 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0012_auto_20210307_1339'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logogroups',
            name='pupils',
        ),
        migrations.RemoveField(
            model_name='logogroups',
            name='teacher',
        ),
        migrations.AddField(
            model_name='logogroups',
            name='name',
            field=models.TextField(null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='pupil',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_panel.logogroups'),
        ),
    ]
