# Generated by Django 3.1.7 on 2021-03-07 11:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('admin_panel', '0013_auto_20210307_1400'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logogroups',
            name='name',
        ),
        migrations.RemoveField(
            model_name='pupil',
            name='group',
        ),
        migrations.AddField(
            model_name='logogroups',
            name='pupil',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_panel.pupil'),
        ),
        migrations.AddField(
            model_name='logogroups',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
