# Generated by Django 3.1.7 on 2021-03-10 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0015_auto_20210310_1843'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
