# Generated by Django 3.1.7 on 2021-03-11 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0023_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
    ]
