# Generated by Django 3.1.7 on 2021-03-17 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0026_auto_20210317_1322'),
    ]

    operations = [
        migrations.RenameField(
            model_name='logogroups',
            old_name='teacher',
            new_name='profile',
        ),
    ]
