# Generated by Django 3.1.7 on 2021-03-17 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0030_auto_20210317_1114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='pupils',
        ),
    ]
