# Generated by Django 3.1.7 on 2021-03-17 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0027_auto_20210317_1821'),
        ('admin_panel', '0031_remove_profile_pupils'),
    ]

    operations = [
    ]
