# Generated by Django 3.2 on 2021-04-08 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0034_profile_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='LogoGroups',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
