# Generated by Django 3.1.7 on 2021-04-14 10:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('admin_panel', '0038_logogroups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logogroups',
            name='custom_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Учитель'),
        ),
        migrations.AlterField(
            model_name='logogroups',
            name='pupil',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='admin_panel.pupil', verbose_name='Ученик'),
        ),
    ]
