# Generated by Django 3.1.7 on 2021-04-22 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArticulatoryMotorSkills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repeat', models.IntegerField(blank=True, choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3')], null=True, verbose_name='Повтори')),
            ],
        ),
        migrations.CreateModel(
            name='Diagnostics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_create', models.DateField(auto_now=True)),
            ],
        ),
    ]
