# Generated by Django 3.1.7 on 2021-03-05 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pupil',
            name='name',
            field=models.CharField(max_length=50, null=True, verbose_name='я'),
        ),
    ]
