# Generated by Django 3.1.7 on 2021-05-28 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0003_pupil_home_address'),
        ('main', '0002_delete_articulatorymotorskills'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnostics',
            name='pupil_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_panel.pupil', verbose_name='Ученик'),
        ),
    ]
