# Generated by Django 3.1.7 on 2021-03-03 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210303_1836'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='class',
            options={'verbose_name': 'Класс', 'verbose_name_plural': 'Классы'},
        ),
        migrations.AlterField(
            model_name='class',
            name='number_class',
            field=models.IntegerField(verbose_name='Номер класса'),
        ),
        migrations.AlterField(
            model_name='pupil',
            name='class_number',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.class', verbose_name='Класс'),
        ),
    ]
