# Generated by Django 3.1.7 on 2021-03-05 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_pupil_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='pupil',
            name='date',
            field=models.DateField(null=True, verbose_name='Дата'),
        ),
    ]
