# Generated by Django 3.1.7 on 2021-05-28 13:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0003_diagnostics_pupil_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diagnostics',
            options={'verbose_name': 'Диагностика', 'verbose_name_plural': 'Диагностики'},
        ),
        migrations.AddField(
            model_name='diagnostics',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Учитель'),
        ),
        migrations.AlterField(
            model_name='diagnostics',
            name='date_create',
            field=models.DateField(auto_now=True, verbose_name='Дата создания'),
        ),
    ]
