# Generated by Django 3.1.7 on 2021-05-28 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210528_1642'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diagnostics',
            old_name='date_create',
            new_name='date_of_creation',
        ),
    ]
