# Generated by Django 3.1.7 on 2021-04-09 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_customuser_patronymic'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='password1',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='customuser',
            name='password2',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
