# Generated by Django 3.1.7 on 2021-05-28 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210528_1653'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatesOfFunctions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hearing', models.TextField(null=True, verbose_name='Слух')),
                ('vision', models.TextField(null=True, verbose_name='Зрение')),
                ('breath', models.TextField(null=True, verbose_name='Дыхание')),
                ('voice', models.TextField(null=True, verbose_name='Голос')),
                ('prosody', models.TextField(null=True, verbose_name='Просодика')),
                ('articulation_apparatus', models.TextField(null=True, verbose_name='Артикуляционный аппарат')),
                ('motor_skills', models.TextField(null=True, verbose_name='Моторика')),
                ('additional_information', models.TextField(null=True, verbose_name='Дополнительная информация')),
                ('diagnostic_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.diagnostics', verbose_name='ID_Диагностика')),
            ],
        ),
    ]
