# Generated by Django 3.1.7 on 2021-06-03 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_statesoffunctions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='statesoffunctions',
            options={'verbose_name': 'Состояние функций', 'verbose_name_plural': 'Состояния функций'},
        ),
        migrations.AlterField(
            model_name='statesoffunctions',
            name='additional_information',
            field=models.TextField(blank=True, verbose_name='Дополнительная информация'),
        ),
        migrations.AlterField(
            model_name='statesoffunctions',
            name='articulation_apparatus',
            field=models.TextField(blank=True, verbose_name='Артикуляционный аппарат'),
        ),
        migrations.AlterField(
            model_name='statesoffunctions',
            name='breath',
            field=models.TextField(blank=True, verbose_name='Дыхание'),
        ),
        migrations.AlterField(
            model_name='statesoffunctions',
            name='diagnostic_id',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='main.diagnostics', verbose_name='ID_Диагностика'),
        ),
        migrations.AlterField(
            model_name='statesoffunctions',
            name='hearing',
            field=models.TextField(blank=True, verbose_name='Слух'),
        ),
        migrations.AlterField(
            model_name='statesoffunctions',
            name='motor_skills',
            field=models.TextField(blank=True, verbose_name='Моторика'),
        ),
        migrations.AlterField(
            model_name='statesoffunctions',
            name='prosody',
            field=models.TextField(blank=True, verbose_name='Просодика'),
        ),
        migrations.AlterField(
            model_name='statesoffunctions',
            name='vision',
            field=models.TextField(blank=True, verbose_name='Зрение'),
        ),
        migrations.AlterField(
            model_name='statesoffunctions',
            name='voice',
            field=models.TextField(blank=True, verbose_name='Голос'),
        ),
    ]
