# Generated by Django 3.2 on 2021-04-09 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20210409_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='status',
            field=models.BooleanField(null=True, verbose_name='Статус'),
        ),
    ]
