# Generated by Django 3.1.7 on 2021-03-05 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_pupil_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pupil',
            name='date',
        ),
        migrations.RemoveField(
            model_name='pupil',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='pupil',
            name='last_name',
        ),
    ]
