# Generated by Django 3.1.7 on 2021-06-03 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20210603_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statesoffunctions',
            name='diagnostic_id',
            field=models.ForeignKey(default=127, on_delete=django.db.models.deletion.CASCADE, to='main.diagnostics', verbose_name='ID_Диагностика'),
            preserve_default=False,
        ),
    ]
