# Generated by Django 3.1.7 on 2021-04-12 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_customuser_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='status',
        ),
    ]
