# Generated by Django 3.1.7 on 2021-03-05 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20210306_0023'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pupil',
        ),
    ]
