# Generated by Django 3.1.7 on 2021-06-03 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20210603_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnostics',
            name='date_of_creation',
            field=models.DateField(verbose_name='Дата создания'),
        ),
    ]
