# Generated by Django 3.1.7 on 2021-04-22 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_customuser_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticulatoryMotorSkills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repeat', models.IntegerField(blank=True, null=True, verbose_name='Повтори')),
            ],
        ),
    ]
