# Generated by Django 3.1.7 on 2021-06-03 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20210603_1236'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnostics',
            name='current_class',
            field=models.IntegerField(null=True, verbose_name='Текущий класс'),
        ),
    ]
