# Generated by Django 3.1.7 on 2021-04-22 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_articulatorymotorskills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulatorymotorskills',
            name='repeat',
            field=models.FloatField(blank=True, null=True, verbose_name='Повтори'),
        ),
    ]
