# Generated by Django 3.1.7 on 2021-06-07 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_diagnostics_current_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statesoffunctions',
            name='diagnostic_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.diagnostics', verbose_name='ID_Диагностика'),
        ),
    ]
