# Generated by Django 3.1.7 on 2021-07-04 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20210607_1203'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diagnostics',
            old_name='pupil_id',
            new_name='pupil',
        ),
        migrations.RenameField(
            model_name='diagnostics',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='statesoffunctions',
            name='diagnostic_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.diagnostics', verbose_name='ID_Диагностика'),
        ),
    ]
