# Generated by Django 3.1.7 on 2021-07-04 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20210704_2249'),
    ]

    operations = [
        migrations.RenameField(
            model_name='statesoffunctions',
            old_name='diagnostic_id',
            new_name='diagnostic',
        ),
    ]
