# Generated by Django 3.1.7 on 2021-04-22 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20210422_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulatorymotorskills',
            name='repeat',
            field=models.IntegerField(blank=True, choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3')], null=True, verbose_name='Повтори'),
        ),
    ]
