# Generated by Django 3.1.7 on 2021-07-06 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20210704_2251'),
    ]

    operations = [
        migrations.CreateModel(
            name='SensoMotorLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phonemic_perception', models.CharField(blank=True, max_length=100, null=True, verbose_name='Фонематическое воспритятие')),
                ('sound_pronunciation', models.CharField(blank=True, max_length=100, null=True, verbose_name='Звукопроизношение')),
                ('sound_syllable_structure', models.CharField(blank=True, max_length=100, null=True, verbose_name='Звуко-слоговая структура')),
                ('diagnostic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.diagnostics', verbose_name='ID_Диагностика')),
            ],
            options={
                'verbose_name': 'Сенсо-моторный уровень',
                'verbose_name_plural': 'Сенсо-моторный уровень',
            },
        ),
    ]
