# Generated by Django 3.1.7 on 2021-08-12 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_remove_statesoffunctions_additional_information'),
    ]

    operations = [
        migrations.AddField(
            model_name='statesoffunctions',
            name='additional_information',
            field=models.TextField(blank=True, null=True, verbose_name='Дополнительная информация'),
        ),
    ]
