# Generated by Django 3.2.6 on 2021-08-27 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_auto_20210813_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensomotorlevel',
            name='phonemic_perception',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Фонематическое воспритятие'),
        ),
    ]
