# Generated by Django 3.2.6 on 2021-09-06 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_alter_sensomotorlevel_phonemic_perception'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensomotorlevel',
            name='sound_pronunciation',
            field=models.CharField(blank=True, max_length=350, null=True, verbose_name='Звукопроизношение'),
        ),
    ]
