# Generated by Django 3.2.6 on 2021-09-06 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_alter_sensomotorlevel_phonemic_perception'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensomotorlevel',
            name='phonemic_perception',
            field=models.CharField(blank=True, default='0:&1:&2:&3:&4:&5:&6:&7:&8:&9:&10:&11:&12:', max_length=100, null=True, verbose_name='Фонематическое воспритятие'),
        ),
    ]
