# Generated by Django 3.2.7 on 2021-09-08 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_alter_sensomotorlevel_phonemic_perception'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensomotorlevel',
            name='articulatory_motor',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Артикуляционная моторика'),
        ),
    ]
