# Generated by Django 3.2.7 on 2021-09-22 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_sensomotorlevel_articulatory_motor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sensomotorlevel',
            old_name='articulatory_motor',
            new_name='articulatoryMotor',
        ),
        migrations.RenameField(
            model_name='sensomotorlevel',
            old_name='phonemic_perception',
            new_name='phonemicPerception',
        ),
        migrations.RenameField(
            model_name='sensomotorlevel',
            old_name='sound_pronunciation',
            new_name='soundPronunciation',
        ),
        migrations.RenameField(
            model_name='sensomotorlevel',
            old_name='sound_syllable_structure',
            new_name='soundSyllableStructure',
        ),
    ]
